name: ridemitra
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  http: ^1.2.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
flutter:
  uses-material-design: true
